[project]
name = "events"
channels = [
    "https://repo.prefix.dev/ecoscope-workflows/",
    "conda-forge",
]
platforms = ["linux-64", "linux-aarch64", "osx-arm64"]

[dependencies]
# todo: test env
curl = "*"
yq = "*"
# todo: default env
ecoscope-workflows-core = { version = "0.0.28", channel = "https://repo.prefix.dev/ecoscope-workflows/" }
ecoscope-workflows-ext-ecoscope = { version = "0.0.28", channel = "https://repo.prefix.dev/ecoscope-workflows/" }

[tasks]
compile = { cmd = "./dev/recompile.sh --install" }
recompile = { cmd = "./dev/recompile.sh --update" }

pytest-app = { cmd = "./dev/pytest.sh events 'app'" }
pytest-cli = { cmd = "./dev/pytest.sh events 'cli'" }

docker-build = { cmd = "./dev/docker-build.sh events" }
docker-run = { cmd = "./dev/docker-run.sh events" }

curl-invoke = { cmd = "./dev/curl-invoke-docker.sh" }
